version: '3.1'
networks:
  appenv:
volumes:
  dados:
services:
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db001
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dados:/var/lib/mysql
    networks:
      - appenv
    ports:
      - 33060:3306

  backend:
    image: node:8.1
    volumes:
      - ./node:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node index.js"
    networks:
      - appenv
    depends_on:
      - db

  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 85:80
    networks:
    - appenv
    depends_on:
      - backend
